const isaiah2 = `
<p id='ch'>Inside</p>
<p id='ch'>$nbsp starvation</p>
<p id='ch'>$nbsp $nbsp are</p>
<p id='ch'>$nbsp $nbsp $nbsp individual</p>
<p id='ch'>$nbsp $nbsp $nbsp $nbsp attitudes.</p>
<p id='ch'>$nbsp $nbsp $nbsp $nbsp $nbsp Hippocritical</p>
<p id='ch'>$nbsp $nbsp $nbsp $nbsp attitudes.</p>
<p id='ch'>$nbsp $nbsp $nbsp Individuals</p>
<p id='ch'>$nbsp $nbsp are</p>
<p id='ch'>$nbsp starving</p>
<p id='ch'>inside.</p> `;